## Definición de los stages
stages:
  - intermediate
  - primary
  - feature
  - model_input
  - models
  - model_selection


## Definición de las variables de entorno
# Configuración común para todos los stages
.common_setup: &common_setup
  - apt-get update -y && apt-get install -y python3 python3-pip python3-venv
  - python3 -m venv proyecto_segmentacion
  - . proyecto_segmentacion/bin/activate
  - pip install --upgrade pip
  - pip install PyYAML==6.0.0 pyarrow==15.0.0 pandas==2.2.0

# Instalación específica para el stage intermediate
.intermediate_setup:
  script:
    - *common_setup
    - pip install polars==0.20.25

# Instalación específica para el stage primary
.primary_setup:
  script:
    - *common_setup
    - pip install transformers==4.42.4

# Instalación específica para el stage feature
.feature_setup:
  script:
    - *common_setup
    - pip install scikit-learn==1.4.0 feature_engine==1.8.0 polars==0.20.25 pandas==2.2.0

# Instalación específica para el stage model_input
.model_input_setup:
  script:
    - *common_setup
    - pip install pandas==2.2.0

# Instalación específica para el stage models
.models_setup:
  script:
    - *common_setup
    - pip install pytorch==2.3.1 accelerate==0.32.1 transformers==4.42.4 scikit-learn==1.4.0


## Ejecución de los stages
intermediate_pipeline:
  image: python:3.10.0
  stage: intermediate
  before_script:
    - *intermediate_setup
  script:
    - echo "INICIO PIPELINE INTERMEDIATE"
    - . nlp/bin/activate
    - nlp/bin/python3 __main__.py 'Pipeline Intermediate'
    - echo "FIN PIPELINE INTERMEDIATE"

primary_pipeline:
  image: python:3.10.0
  stage: primary
  before_script:
    - *primary_setup
  script:
    - echo "INICIO PIPELINE PRIMARY"
    - . nlp/bin/activate
    - nlp/bin/python3 __main__.py 'Pipeline Primary'
    - echo "FIN PIPELINE PRIMARY"

feature_pipeline:
  image: python:3.10.0
  stage: feature
  before_script:
    - *feature_setup
  script:
    - echo "INICIO PIPELINE FEATURE"
    - . nlp/bin/activate
    - nlp/bin/python3 __main__.py 'Pipeline Feature'
    - echo "FIN PIPELINE FEATURE"

model_input_pipeline:
  image: python:3.10.0
  stage: model_input
  before_script:
    - *model_input_setup
  script:
    - echo "INICIO PIPELINE MODEL INPUT"
    - . nlp/bin/activate
    - nlp/bin/python3 __main__.py 'Pipeline Model Input'
    - echo "FIN PIPELINE MODEL INPUT"

models_pipeline:
  image: python:3.10.0
  stage: models
  before_script:
    - *models_setup
  script:
    - echo "INICIO PIPELINE MODELS"
    - . nlp/bin/activate
    - nlp/bin/python3 __main__.py 'Pipeline Models'
    - echo "FIN PIPELINE MODELS"