name: nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pyarrow=15.0.0
  - jupyter=1.0.0
  - ipykernel=6.29.0
  - pandas=2.2.0
  - openpyxl=3.1.0
  - numpy=1.26.0
  - pyyaml=6.0.0
  - seaborn=0.13.2
